---
driver:
  name: ec2
  instance_type: t2.small
  security_group_ids: 'sg-093e5a2e765821d1f'
  region: 'us-east-1'
  subnet_id: 'subnet-0ff6379b3b6daa100'
  tags:
    Name: Kitchentest

provisioner:
  name: chef_zero
  product_name: chef
  chef_license: accept-no-persist
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: awsLinux
    driver_config:
      image_id: '<%= ENV['awslatest'] %>'
    transport:
      username: ec2-user
  - name: CentosLinux
    driver_config:
      image_id: '<%= ENV['centoslatest'] %>'
    transport:
      username: centos

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
